---
title: "project2"
author: "Miao"
date: "2021/7/11"
output:
  pdf_document:
    latex_engine: pdflatex
    number_sections: yes
  html_document:
    df_print: paged
  word_document: default
fig_caption: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE, warning = FALSE, message = FALSE, comment = NA)
```

```{r libraries,echo = FALSE}
library(tidyverse)
library(moderndive)
library(skimr)
library(kableExtra)
library(gridExtra)
library(devtools)
library(magrittr)
library(ggplot2)
library(maps)
library(RColorBrewer)
library(viridis)
library(ggpubr)
library(GGally)
library(corrplot)
library(knitr)
library(olsrr)
library(data.table)
library(moderndive)
library(ggfortify)
library(diagram)
library(ggthemes)
library(cowplot)
library(showtext)
```

```{R data, echo = TRUE, eval = TRUE, warning = TRUE, message = TRUE}
#read the file
dat<-read.csv("./dataset9.csv")
#add the score column,if rating>7,then 1,else 0
dat<-mutate(dat,score=ifelse(rating>7,1,0))
#replace NA with mean value in length column 
dat$length[is.na(dat$length)]<-mean(dat$length,na.rm = TRUE)
dat$scorename[dat$score==1] <- "greater than 7"
dat$scorename[dat$score==0] <- "lower than 7"
```

# Introduction {#sec:Intro}

This is introduction.

# Main Definitions And Method {#sec:MET}

# objective

objective objective

# variables

this is `variable` part!

# Exploratory Data Analysis {#sec:EDA}
```{r table, echo = FALSE}
#The table of year
dat %>%
summarise(name="Year", n=n(),Mean=round(mean(year),digits=1), St.Dev=round(sd(year),digits=1),
Min=min(year), Q1 = quantile(year,0.25), Median=median(year),
Q3 = quantile(year,0.75), Max=max(year))-> table1

#The table of length
dat %>%
summarise(name="Length", n=n(),Mean=round(mean(length),digits=1), St.Dev=round(sd(length),digits=1),
Min=min(length), Q1 = quantile(length,0.25), Median=median(length),
Q3 = quantile(length,0.75), Max=max(length))-> table2

#The table of budget
dat %>%
summarise(name="Budget", n=n(),Mean=round(mean(budget),digits=1), St.Dev=round(sd(budget),digits=1),
Min=min(budget), Q1 = quantile(budget,0.25), Median=median(budget),
Q3 = quantile(budget,0.75), Max=max(budget))-> table3

#The table of votes
dat %>%
summarise(name="Votes", n=n(),Mean=round(mean(votes),digits=1), St.Dev=round(sd(votes),digits=1),
Min=min(votes), Q1 = quantile(votes,0.25), Median=median(votes),
Q3 = quantile(votes,0.75), Max=max(votes))-> table4

#The table of rating
dat %>%
summarise(name="Rating", n=n(),Mean=round(mean(rating),digits=1), St.Dev=round(sd(rating),digits=1),
Min=min(rating), Q1 = quantile(rating,0.25), Median=median(rating),
Q3 = quantile(rating,0.75), Max=max(rating))-> table5

#Combining the two tables
dplyr::union_all(table1,table2) -> table
dplyr::union_all(table,table3) -> table
dplyr::union_all(table,table4) -> table
dplyr::union_all(table,table5) -> table

table%>%
  kable(caption = '\\label{tab:summaries} Summary statistics',  align = c("c", "c", "c")) %>%
kable_styling(latex_options = "hold_position")
```

```{r histogram1, echo = FALSE, eval = TRUE,fig.align = "center", fig.cap = "\\label{fig:histogramyear} Year histogram",out.heighth='75%',out.width='75%',fig.pos = 'H'}
histogram1 <- ggplot(dat, aes(year,fill=genre))+geom_histogram()+
  guides(fill = FALSE) +
  theme_economist() +
  scale_fill_gdocs()+
  guides(fill=guide_legend())+ 
  theme(plot.title = element_text(size = 10,hjust = 0.5, face = "bold"),
        text = element_text(size = 10,face = "bold",hjust = 0.5),
        axis.title.y = element_text(face = "bold",hjust = 0.5),
        axis.text.x = element_text(size =10,face ="bold"))
histogram1
```

```{r histogram2, echo = FALSE, eval = TRUE,fig.align = "center", fig.cap = "\\label{fig:histogramyLength} Length histogram",out.heighth='75%',out.width='75%',fig.pos = 'H'}
histogram2 <- ggplot(dat, aes(log(length),fill=genre))+geom_histogram()+
  guides(fill = FALSE) +
  theme_economist() +
  scale_fill_gdocs()+
  guides(fill=guide_legend())+ 
  theme(plot.title = element_text(size = 10,hjust = 0.5, face = "bold"),
        text = element_text(size = 10,face = "bold",hjust = 0.5),
        axis.title.y = element_text(face = "bold",hjust = 0.5),
        axis.text.x = element_text(size =10,face ="bold"))
histogram2
```

```{r histogram3, echo = FALSE, eval = TRUE,fig.align = "center", fig.cap = "\\label{fig:histogramVotes} Votes histogram",out.heighth='75%',out.width='75%',fig.pos = 'H'}
histogram3 <- ggplot(dat, aes(log(votes),fill=genre))+geom_histogram()+
  guides(fill = FALSE) +
  theme_economist() +
  scale_fill_gdocs()+
  guides(fill=guide_legend())+ 
  theme(plot.title = element_text(size = 10,hjust = 0.5, face = "bold"),
        text = element_text(size = 10,face = "bold",hjust = 0.5),
        axis.title.y = element_text(face = "bold",hjust = 0.5),
        axis.text.x = element_text(size =10,face ="bold"))
histogram3
```




